---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radio
spec:
  rules:
  - host: radio.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radio-ui
            port:
              number: 80
      - path: /stream
        pathType: Prefix
        backend:
          service:
            name: radio-server
            port:
              number: 80
      - path: /now-playing
        pathType: Prefix
        backend:
          service:
            name: radio-server
            port:
              number: 80
      - path: /control
        pathType: Prefix
        backend:
          service:
            name: radio-server
            port:
              number: 80
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: radio-server
            port:
              number: 80
