---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radio
spec:
  rules:
  - host: radio.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radio
            port:
              number: 80
