---
apiVersion: v1
kind: Service
metadata:
  name: radio-server
  labels:
    app: radio-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: radio-server
---
apiVersion: v1
kind: Service
metadata:
  name: radio-ui
  labels:
    app: radio-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: radio-ui
