---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radio
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    dashboard.shokohsc.home/name: dev-radio
    dashboard.shokohsc.home/url: https://dev.radio.shokohsc.home
    dashboard.shokohsc.home/icon: wrench
spec:
  rules:
  - host: dev.radio.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radio
            port:
              number: 80
  tls:
  - hosts:
    - dev.radio.shokohsc.home
    secretName: radio-cert
